import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav class="bg-gray-200 shadow shadow-gray-300 w-100 px-8 md:px-auto">
          <div class="md:h-16 h-28 mx-auto md:px-4 container flex items-center justify-center flex-wrap md:flex-nowrap">
            <div class="text-gray-500 order-3 w-full md:w-auto md:order-2 flex">
              <ul class="flex font-semibold justify-between">
                <li class="md:px-4 md:py-2 hover:text-indigo-400"><Link href="/">Home</Link></li>
                <li class="md:px-4 md:py-2 hover:text-indigo-400"><Link href="/snippets/new">New Snippet</Link></li>
              </ul>
            </div>
            </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
